### ISSUE TITLE
AppBarLayout 快速滑动时，下面的RecyclerView可以正常滚动，但是会突然停止，慢速滑动时RecyclerView是正常的

### ISSUE THREAD

**Issue by wangrui460** [iamyours/FlingAppBarLayout#5]
拿大众点评app举个例子，快速滑动上面的 AppBarLayout，AppBarLayout收缩完成后，下面的 ViewPager 可以继续滑动，直到均匀减速到停止。

使用 FlingAppBarLayout，快速滑动上面的 FlingAppBarLayout，FlingAppBarLayout收缩完成后，下面的 ViewPager 可以继续滑动，但是会突然停止~

**Comment by iamyours** [comment]
你说得突然停止是不是下面还有内容，但是滑动停止了？

**Comment by wangrui460** [comment]
是的

**Comment by iamyours** [comment]
原先最大距离限制为5000，现在改成`Integer.MAX_VALUE / 2 `，见[HeaderBehavior.java](https://github.com/iamyours/FlingAppBarLayout/blob/master/flingappbarlayout/src/main/java/io/github/iamyours/flingappbarlayout/HeaderBehavior.java)

```
final boolean fling(CoordinatorLayout coordinatorLayout, V layout, int minOffset,
                        int maxOffset, float velocityY) {
       ...
        int fixedMin = velocityY < 0 ? minOffset - Integer.MAX_VALUE / 2 : minOffset;
        mScroller.fling(
                0, getTopAndBottomOffset(), // curr
                0, Math.round(velocityY), // velocity.
                0, 0, // x
                fixedMin, maxOffset); // y
...
    }
```
