### ISSUE TITLE
ViewPager遇到的问题 

### ISSUE THREAD

**Issue by mallxiaodoudou** [iamyours/FlingAppBarLayout#6]
如果ViewPager中一个fragment中的recyclerview的数据很短，不满一屏，那么在这个recyclerView中会有滑动冲突问题。下拉不会拉出appbarLayout而是直接触发smartRefreshLayout

复现：
在Demo中ViewPagerFlingActivity的xml中 根布局加入smartRefreshLayout，然后再NestedScrollViewFragment中去掉一个图片，只用一张图片，这样就不满一屏了，然后你上滑下滑操作试试

**Comment by iamyours** [comment]
按照你的方式试了下，没发现你说的滑动冲突，`SmartRefreshLayout`已经做过适配，在`MyRefreshLayout`下，如果还是有问题，你可以fork代码然后改成具体你说的情况，到时候我看下

**Comment by mallxiaodoudou** [comment]
解决了特意说一下，使用了你自定义的MySmartRefreshLayout,就可以了，我用的原来的SmartRefresh.就是要改到指定版本，我用的1.1.0。MySmartRefreshLayout就有些方法不在了，用你的版本就可以了，感谢
